Added calendar
js-tasks-ru/htmlcss-20230411_alexander-lysyuk pull request #7
Opened 2023-05-09 15:38 UTC by alysyuk93

2023-05-09 15:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-11 14:39 UTC, GSemikozov requested changes

2023-05-11 14:39 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 36px;
`28 26 32`

2023-05-14 08:16 UTC, alysyuk93 commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 36px;
поправил

2023-05-19 12:12 UTC, alysyuk93 commented
поправил конфликты

2023-05-19 14:38 UTC, GSemikozov approved these changes

2023-05-19 14:38 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-05-19 14:42 UTC, GSemikozov approved these changes

2023-05-19 14:42 UTC, GSemikozov approved these changes

2023-05-19 14:42 UTC, merged